### ISSUE TITLE
Provide plotting scripts for data generated by lockhammer sweeps

### ISSUE THREAD

**Issue by geoffreyblake** [ARM-software/synchronization-benchmarks#46]
The data generated by the sweep scripts is not documented well and there should be a parsing script provided.

**Comment by zoybai** [comment]
Request 1: It would be great if you can share the scripts that make sense of the output when lockhammer tests are run. - We can release the ipython notebook which can parse and graph the csv file.

Request 2: The script in the git that runs a sweep and creates a csv file should at least put headers on the columns. - We will add headers as first line and ignore it in ipython notebook.

**Comment by zoybai** [comment]
Please help review this pull request:
https://github.com/ARM-software/synchronization-benchmarks/pull/48

**Comment by zoybai** [comment]
Pull request #48 has been merged.
