### ISSUE TITLE
Should we warmup the thread before lock testing?

### ISSUE THREAD

**Issue by zoybai** [ARM-software/synchronization-benchmarks#9]
The testing time for 1 ~ 8 threads is so small (0.1~0.5ms) that we saw a large skew (lock acquire average latency in ns) between 1 thread and max threads for lh_empty test.

lh_empty is overhead test which should yield stable lock acquire latency. We suspect no enough warmup time caused this.

**Comment by geoffreyblake** [comment]
Pull request has been closed.
